name: CI

on:
    push:
        branches: [master]
    pull_request:
        branches: [master, develop]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2

            - name: Setup Node.js environment
              uses: actions/setup-node@v2.1.4

            - name: Install dependecies
              run: |
                  echo Installing dependencies
                  npm install
            - name: Run tests
              env:
                  SG_API_KEY: ${{ secrets.LOTUS_HOST }}
                  LOTUS_TOKEN: ${{ secrets.LOTUS_TOKEN }}
              run: |
                  echo Testing
                  npm run test
